import transducer
alphabet = transducer.Alphabet()
t = transducer.Transducer()
alphabet.includeSymbol("<n>")
alphabet.includeSymbol("<sg>")
alphabet.includeSymbol("<pl>")
n_sym = alphabet("<n>")
sg_sym = alphabet("<sg>")
pl_sym = alphabet("<pl>")
initial = t.getInitial()
beer = initial
beer = t.insertSingleTransduction(alphabet(ord('b'), ord('b')), beer)
beer = t.insertSingleTransduction(alphabet(ord('e'), ord('e')), beer)
beer = t.insertSingleTransduction(alphabet(ord('e'), ord('e')), beer)
beer = t.insertSingleTransduction(alphabet(ord('r'), ord('r')), beer)
beer = t.insertSingleTransduction(alphabet(0, n_sym), beer)
beer = t.insertSingleTransduction(alphabet(0, sg_sym), beer)
t.setFinal(beer)
beers = t.getInitial()
beers = t.insertSingleTransduction(alphabet(ord('b'),ord('b')), beers)
beers = t.insertSingleTransduction(alphabet(ord('e'), ord('e')), beers)
beers = t.insertSingleTranduction(alphabet(ord('e'), ord('e')), beers)
beers = t.insertSingleTranduction(alphabet(ord('r'), ord('r')), beers)
beers = t.insertSingleTransduction(alphabet(ord('s'), 0), beers)
beers = t.insertSingleTransduction(alphabet(0, n_sym), beers)
beers = t.insertSingleTransduction(alphabet(0, pl_sym), beers)
t.setFinal(beers)

